In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [2]:
# Read Csv Files
movies = pd.read_csv('tmdb_5000_movies.csv') 
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [4]:
movies.shape

(4803, 20)

In [5]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
movies = movies.merge(credits,on='title')

In [7]:
movies.head()
# budget
# homepage
# id
# original_language
# original_title
# popularity
# production_comapny
# production_countries
# release-date(not sure)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [9]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
import ast

In [11]:
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

In [12]:
movies.dropna(inplace=True)

In [13]:
movies['genres'] = movies['genres'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [14]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [15]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}]')

[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}]

In [16]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [17]:
movies['cast'] = movies['cast'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [18]:
movies['cast'] = movies['cast'].apply(lambda x:x[0:3])

In [19]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [20]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [21]:
movies.sample(5)

,movie_id,title,overview,genres,keywords,cast,crew
3980,44594,Barry Munday,"Barry Munday, a libido-driven wage slave who s...","[Comedy, Drama, Romance]","[based on novel, letter, paternity, castration...","[Patrick Wilson, Malcolm McDowell, Judy Greer]",[Chris D'Arienzo]
2230,42618,Sweet Charity,Taxi dancer Charity continues to have Faith in...,"[Comedy, Drama, Music, Romance]","[broken engagement, charity, celebrity, tragic...","[Shirley MacLaine, John McMartin, Ricardo Mont...",[Bob Fosse]
826,8984,Disclosure,A computer specialist is sued for sexual haras...,"[Drama, Thriller, Crime, Mystery, Romance]","[employee, workplace, sexual harassment, intri...","[Michael Douglas, Demi Moore, Donald Sutherland]",[Barry Levinson]
650,345,Eyes Wide Shut,"After Dr. Bill Hartford's wife, Alice, admits ...","[Mystery, Drama]","[life and death, sexual obsession, free love, ...","[Tom Cruise, Nicole Kidman, Madison Eginton]",[Stanley Kubrick]
1933,40001,Mrs. Winterbourne,Connie Doyle is eighteen and pregnant her boyf...,"[Comedy, Romance, Drama]","[role reversal, mistaken identity, train wreck]","[Shirley MacLaine, Ricki Lake, Brendan Fraser]",[Richard Benjamin]

In [22]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [23]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [24]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [25]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" "," ") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" "," ") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" "," ") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" "," ") for i in x])

In [26]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [27]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [28]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [29]:
new_df = movies[['movie_id','title','tags']]

In [30]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

C:\Users\sdkri\AppData\Local\Temp\ipykernel_14280\1824047427.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [31]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [32]:
import nltk

In [33]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [34]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [35]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\sdkri\AppData\Local\Temp\ipykernel_14280\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [36]:
new_df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi scienc fiction cultur clash futur space war space coloni societi space travel futurist romanc space alien tribe alien planet cgi marin soldier battl love affair anti war power relat mind and soul 3d sam worthington zoe saldana sigourney weaver jame cameron'

In [37]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\sdkri\AppData\Local\Temp\ipykernel_14280\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [38]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [39]:
from sklearn.feature_extraction.text import CountVectorizer

In [40]:
# Create and fit CountVectorizer with the original data
cv = CountVectorizer(max_features=5000,stop_words='english')
cv.fit_transform(new_df['tags']).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [41]:
cv.fit_transform(new_df['tags']).toarray().shape

(4806, 5000)

In [42]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [43]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [44]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [45]:
cv.get_feature_names()

D:\Anaconda\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '16th',
 '17',
 '17th',
 '18',
 '18th',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1980',
 '1985',
 '1990',
 '19th',
 '20',
 '200',
 '2009',
 '20th',
 '21st',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '51',
 '60',
 '70',
 'aaron',
 'abandon',
 'abbi',
 'abduct',
 'abigail',
 'abil',
 'abl',
 'aboard',
 'aborigin',
 'abov',
 'abraham',
 'abroad',
 'abus',
 'academ',
 'academi',
 'accent',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'act',
 'action',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adolf',
 'adopt',
 'ador',
 'adrian',
 'adrien',
 'adult',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'affleck',
 'afghanistan',
 'africa',
 'african',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidan',
 'ail',
 'aim',
 'air',
 'aircraft',
 'airplan',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'alba',
 'albert',
 'alcohol',
 'alec',
 'alejandro',
 'alex',
 'alexand',
 'alexi',
 'alfr',
 'ali',
 'alic',
 'alice',
 'alicia',
 'alien',
 'alik',
 'alison',
 'aliv',
 'alive',
 'allan',
 'allen',
 'alli',
 'allianc',
 'allison',
 'allow',
 'alon',
 'alongsid',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'amber',
 'ambigu',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'ami',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amy',
 'ana',
 'analyst',
 'anarch',
 'ancient',
 'anderson',
 'andi',
 'andrea',
 'andrew',
 'android',
 'andré',
 'andy',
 'ang',
 'angarano',
 'angel',
 'angela',
 'angeles',
 'angelina',
 'anger',
 'angri',
 'angst',
 'ani',
 'anim',
 'animals',
 'aniston',
 'ann',
 'anna',
 'annabel',
 'annett',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthropomorph',
 'anti',
 'antoin',
 'anton',
 'antonio',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'appleg',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'aquarium',
 'arab',
 'arbitrari',
 'arch',
 'archaeologist',
 'archeolog',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'ari',
 'ariel',
 'aris',
 'aristocrat',
 'arkin',
 'arm',
 'armand',
 'armi',
 'armor',
 'armstrong',
 'army',
 'arnold',
 'aronofski',
 'arquett',
 'arrang',
 'arrest',
 'arriv',
 'arrog',
 'arrow',
 'art',
 'arthur',
 'articl',
 'artifact',
 'artifici',
 'artist',
 'ash',
 'ashley',
 'ashton',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspir',
 'assassin',
 'assault',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'athlet',
 'atkin',
 'atlant',
 'atom',
 'attack',
 'attacks',
 'attempt',
 'attend',
 'attent',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'audrey',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'austria',
 'author',
 'autism',
 'auto',
 'autobiograph',
 'automobil',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awaken',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'axe',
 'aykroyd',
 'babe',
 'babi',
 'baby',
 'bachchan',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'bacon',
 'bad',
 'bag',
 'bahama',
 'bail',
 'bailey',
 'baker',
 'balanc',
 'baldwin',
 'bale',
 'ball',
 'ballet',
 'balloon',
 'baltimor',
 'ban',
 'bana',
 'band',
 'bandera',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bar',
 'barbara',
 'bardem',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrier',
 'barrymor',
 'bart',
 'bas',
 'base',
 'basebal',
 'basement',
 'basing',
 'basketbal',
 'bassett',
 'bat',
 'bate',
 'bateman',
 'bath',
 'bathroom',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'beam',
 'bean',
 'bear',
 'beard',
 'beast',
 'beat',
 'beatti',
 'beau',
 'beauti',
 'beautiful',
 'beauty',
 'becam',
 'becaus',
 'beck',
 'becker',
 'becki',
 'beckinsal',
 'becom',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'bello',
 'belong',
 'belov',
 'belt',
 'ben',
 'bend',
 'bene',
 'beneath',
 'benefit',
 'benicio',
 'benjamin',
 'bennett',
 'bent',
 'bentley',
 'berg',
 'bergman',
 'berlin',
 'bernal',
 'berni',
 'berri',
 'best',
 'bet',
 'beth',
 'betray',
 'bett',
 'bettani',
 'better',
 'betti',
 'beverli',
 'bibl',
 'biblic',
 'bicycl',
 'biehn',
 'biel',
 'big',
 'bigg',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'billi',
 'billion',
 'billionair',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmail',
 'blade',
 'blair',
 'blake',
 'blame',
 'blanchett',
 'bledel',
 'blend',
 'bless',
 'blind',
 'bliss',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodthirsti',
 'bloom',
 'blow',
 'blue',
 'blunt',
 'board',
 'boat',
 'bob',
 'bobbi',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'bonham',
 'bonni',
 'book',
 'booth',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'bosworth',
 'botch',
 'bottl',
 'bound',
 'boundari',
 'bounti',
 'bout',
 'bow',
 'bower',
 'bowl',
 'bowman',
 'box',
 'boxer',
 'boy',
 'boyd',
 'boyfriend',
 'boyl',
 'boys',
 'brad',
 'bradford',
 'bradley',
 'brain',
 'branagh',
 'brand',
 'brando',
 'brandon',
 'bratt',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breast',
 'breath',
 'breed',
 'brenda',
 'brendan',
 'brent',
 'breslin',
 'brett',
 'brian',
 'bride',
 'bridesmaid',
 'bridg',
 'bridget',
 'brie',
 'brief',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britt',
 'brittani',
 'broadbent',
 'broadcast',
 'broadway',
 'broderick',
 'brodi',
 'broke',
 'broken',
 'broker',
 'brolin',
 'bronx',
 'brook',
 'brooklyn',
 'broom',
 'brosnan',
 'brothel',
 'brother',
 'brothers',
 'brought',
 'brown',
 'bruce',
 'bruno',
 'brutal',
 'bryan',
 'bryce',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'budget',
 'buffalo',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bullock',
 'bumbl',
 'bunni',
 'burglar',
 'buri',
 'burk',
 'burn',
 'burstyn',
 'burt',
 'burton',
 'buscemi',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butcher',
 'butler',
 'butt',
 'buy',
 'buzz',
 'byrn',
 'caan',
 'cabin',
 'cabl',
 'caesar',
 'cage',
 'cain',
 'cairo',
 'cal',
 'california',
 'calli',
 'calm',
 'calvin',
 'cam',
 'camcord',
 'came',
 'cameo',
 'camera',
 'cameraman',
 'cameron',
 'camp',
 'campaign',
 'campbel',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'canin',
 'cannib',
 'cannon',
 'capabl',
 'caper',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'car',
 'card',
 'care',
 'career',
 'carefre',
 'carel',
 'caretak',
 'carey',
 'cargo',
 'cari',
 'caribbean',
 'carl',
 'carla',
 'carlo',
 'carmen',
 'carol',
 'carolin',
 'carolina',
 'carpent',
 'carradin',
 'carrey',
 'carri',
 'carrie',
 'carrier',
 'carrol',
 'cartel',
 'carter',
 'cartoon',
 'case',
 'casey',
 'cash',
 'casino',
 'cassidi',
 'cast',
 'castl',
 'castle',
 'casual',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cate',
 'catherin',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'cavemen',
 'caviezel',
 'cedric',
 'celebr',
 'cell',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'cera',
 'ceremoni',
 'certain',
 'cesar',
 'chad',
 'chain',
 'chainsaw',
 'chair',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chan',
 'chanc',
 'chance',
 'chandrasekhar',
 'chang',
 'change',
 'changes',
 'channel',
 'chao',
 'chaos',
 'chaotic',
 'chapman',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charliz',
 'charlott',
 'charm',
 'chart',
 'chase',
 'chastain',
 'chat',
 'chauffeur',
 'chazz',
 'cheadl',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chelsea',
 'chemic',
 'chen',
 'cher',
 'cheryl',
 'chestnut',
 'chevi',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childhood',
 'children',
 'chill',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chiwetel',
 'chloe',
 'chloë',
 'chocol',
 'choic',
 'choice',
 'choir',
 'choos',
 'chopra',
 'chosen',
 'chow',
 'chri',
 'christ',
 'christensen',
 'christian',
 'christin',
 'christina',
 'christma',
 'christmas',
 'christoph',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'cigar',
 'cigarett',
 'cillian',
 'cinema',
 'cinemat',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'claim',
 'clair',
 'clan',
 'clare',
 'clark',
 'clash',
 'class',
 'classic',
 'classmat',
 'classroom',
 'clau',
 'claud',
 'claudia',
 'clay',
 'clean',
 'clear',
 'clerk',
 'client',
 'cliff',
 'climat',
 'climb',
 'clint',
 'clive',
 'clock',
 'clone',
 'clooney',
 'close',
 'closer',
 'closet',
 'cloud',
 'clown',
 'club',
 'clue',
 'clumsi',
 'clutch',
 'coach',
 'coal',
 'coast',
 'cocain',
 'code',
 'codi',
 'coen',
 'coffin',
 'cohen',
 'col',
 'cold',
 'cole',
 'coleman',
 'colin',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collett',
 'collid',
 'collin',
 'collis',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'columbu',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'coming',
 'command',
 'commando',
 'commerci',
 'commit',
 'common',
 'commun',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compuls',
 'comput',
 'conan',
 'concentr',
 'concern',
 'concert',
 'condit',
 'condition',
 'confeder',
 'confer',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'congress',
 'connect',
 'connel',
 'connelli',
 'conneri',
 'conni',
 'connor',
 'conquer',
 'conrad',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'contest',
 'continu',
 'contract',
 'control',
 'controversi',
 ...]

In [46]:
stem('In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy Science Fiction culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d Sam Worthington Zoe Saldana Sigourney Weaver James Cameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi scienc fiction cultur clash futur space war space coloni societi space travel futurist romanc space alien tribe alien planet cgi marin soldier battl love affair anti war power relat mind and soul 3d sam worthington zoe saldana sigourney weaver jame cameron'

In [47]:
from sklearn.metrics.pairwise import cosine_similarity

In [48]:
similarity = cosine_similarity(vectors)

In [49]:
similarity.shape

(4806, 4806)

In [50]:
sorted(similarity[0],reverse=True)

[1.0000000000000002,
 0.490079493105597,
 0.4113063728303113,
 0.3880712182748949,
 0.3879852850993631,
 0.380442955126341,
 0.3776782946782564,
 0.3651338997452622,
 0.35840861465369933,
 0.3375152561397402,
 0.3363311128027262,
 0.3311330892662609,
 0.32780503405359285,
 0.3248113180671166,
 0.3231104224953257,
 0.32002844823759896,
 0.3162994973926084,
 0.31264094565852324,
 0.309344112444873,
 0.3084235851091745,
 0.30117351663461456,
 0.3008967382970351,
 0.30066001672920123,
 0.2974059387397313,
 0.2938769068226293,
 0.2931423266123845,
 0.29139711855430955,
 0.29135827337403253,
 0.29135827337403253,
 0.29134939036443036,
 0.29019050004400465,
 0.2896811091620759,
 0.2866297455600074,
 0.28617573573616945,
 0.28587970431159826,
 0.2845551966122361,
 0.2838874869788344,
 0.2755193843889919,
 0.2752988806446741,
 0.27042102426470555,
 0.2605842192811105,
 0.2604940361258638,
 0.26013299085723596,
 0.25605197407973057,
 0.25391668753850405,
 0.2533558548547658,
 0.2523573072576179,
 0.25174827304761416,
 0.25166114784235827,
 0.24722569302909875,
 0.24678382369818674,
 0.2445579940222592,
 0.24366985862022406,
 0.24333213169614373,
 0.24190495145855573,
 0.24099009325151113,
 0.2409900932515111,
 0.23841582427170782,
 0.23647632573172928,
 0.23498939817841866,
 0.23475647508309563,
 0.23366150977305886,
 0.23366150977305886,
 0.23308661869922598,
 0.23179316248638268,
 0.2300975057565563,
 0.22941573387056172,
 0.22790142204853647,
 0.22663483432464554,
 0.2221308291596596,
 0.22048560307903675,
 0.21886217238860886,
 0.21851870503052434,
 0.21764287503300347,
 0.21371260356627755,
 0.2134163974591771,
 0.21300716142115242,
 0.21179343552183935,
 0.21052631578947364,
 0.20991342856239587,
 0.20991342856239587,
 0.2074364287612964,
 0.2056157234061163,
 0.20519567041703077,
 0.20330507112484944,
 0.20277677641345318,
 0.2013831050778955,
 0.20107367308916743,
 0.20078234442307638,
 0.20073876713674155,
 0.19918863762856526,
 0.19664205760333864,
 0.19619314913492364,
 0.19564639521780736,
 0.19474520942613002,
 0.1938916835823703,
 0.19170644527903719,
 0.1911797782254681,
 0.1908854288927333,
 0.1902214775631705,
 0.1860807318911967,
 0.18560646746692377,
 0.18560646746692377,
 0.18553901099823503,
 0.1842105263157894,
 0.18394180184548975,
 0.1835325870964494,
 0.18301044496560073,
 0.1792043073268497,
 0.17920430732684967,
 0.17920430732684967,
 0.17914359097500465,
 0.17875929966870285,
 0.17844356324383878,
 0.17705013195704258,
 0.17660431427533915,
 0.17624204863381399,
 0.17497830981833887,
 0.17497830981833887,
 0.17492785713532988,
 0.17453202440084278,
 0.17380866549724555,
 0.17342199390482396,
 0.1720618004029213,
 0.17040572913692198,
 0.17040572913692195,
 0.17013926184468012,
 0.17013926184468012,
 0.17013926184468012,
 0.16912752287293456,
 0.16754156331667816,
 0.16747265870207703,
 0.16747265870207703,
 0.16747265870207703,
 0.1657104529998322,
 0.1655665446331305,
 0.16556654463313047,
 0.16531163063339513,
 0.1642706150496122,
 0.16390251702679645,
 0.16390251702679645,
 0.16386838133611553,
 0.16335983103519902,
 0.1630554699247529,
 0.16305546992475287,
 0.16289594138375035,
 0.1615552112476628,
 0.16122923187750418,
 0.16122923187750418,
 0.16122923187750418,
 0.16062314155080884,
 0.15974461276617433,
 0.15929827321607745,
 0.15907119074394444,
 0.1590711907439444,
 0.15897016107942197,
 0.15897016107942197,
 0.15897016107942194,
 0.15806712450288418,
 0.1577233170360112,
 0.15686609568480062,
 0.15650535813672986,
 0.15650535813672986,
 0.1556357543698668,
 0.15511334686589623,
 0.15452877499092174,
 0.15415176003458286,
 0.15415176003458284,
 0.15328483487124145,
 0.15242624470826976,
 0.1514086506444134,
 0.15108988954976368,
 0.1508628572809428,
 0.15058675831730728,
 0.15018785229652765,
 0.14975189244419534,
 0.14974651178226575,
 0.14933692277237473,
 0.14933692277237473,
 0.14930178053803184,
 0.14912022701586516,
 0.14910501299480672,
 0.14900989016981744,
 0.14886458551295736,
 0.14808721943977304,
 0.14768094372379004,
 0.14686837386151166,
 0.14599927901768628,
 0.14567913668701624,
 0.14552644042288462,
 0.14456082739572798,
 0.14456082739572798,
 0.14456082739572795,
 0.14429582107316452,
 0.1442149876003076,
 0.1433848336691011,
 0.14316407166955,
 0.14273582042094193,
 0.14227759830611805,
 0.14180703562423225,
 0.14180703562423225,
 0.14180703562423225,
 0.14159846508095772,
 0.14159846508095772,
 0.14159846508095772,
 0.1404878717372541,
 0.1399422857082639,
 0.13910372101866428,
 0.1383428927732149,
 0.1383428927732149,
 0.1383428927732149,
 0.13809204416652684,
 0.13770565818881086,
 0.13767219793848368,
 0.13710212427677043,
 0.13685996549319585,
 0.13685996549319585,
 0.1361331925293325,
 0.13572417850765922,
 0.1357241785076592,
 0.1357241785076592,
 0.13530201829834765,
 0.13497638119975425,
 0.13497638119975425,
 0.13440323049513725,
 0.1343320988518935,
 0.13425540338526368,
 0.1338548962820509,
 0.1338258447578277,
 0.1337491053485943,
 0.13245323570650439,
 0.13245323570650436,
 0.13200500012082497,
 0.13111122301831463,
 0.13109470506889243,
 0.13006649542861798,
 0.13006649542861798,
 0.13006649542861795,
 0.12988108336653276,
 0.12977713690461,
 0.12977713690461,
 0.12948970103254506,
 0.12905643322991683,
 0.12905643322991683,
 0.1284985132406471,
 0.1281150120837344,
 0.12725695259515554,
 0.12725695259515554,
 0.12725695259515554,
 0.1270760613131036,
 0.12695834376925202,
 0.12667364798453495,
 0.12565617248750863,
 0.12540051368250324,
 0.12519334891679784,
 0.12519334891679784,
 0.12519334891679784,
 0.12487810821089251,
 0.12428283974987417,
 0.12369267399882333,
 0.12361284651454937,
 0.1233919118490934,
 0.12313775728090239,
 0.12297974198582044,
 0.12227899701112961,
 0.1222789970111296,
 0.12166606584807191,
 0.1216660658480719,
 0.1216660658480719,
 0.12105003117656304,
 0.12082986304673732,
 0.1208298630467373,
 0.11980845957463077,
 0.11969747440993464,
 0.11969747440993464,
 0.11969747440993463,
 0.11959121830873495,
 0.11946953821789978,
 0.11946953821789978,
 0.11946953821789978,
 0.11946953821789977,
 0.11920791213585392,
 0.11846977555181844,
 0.11846977555181844,
 0.11838926601105419,
 0.11838926601105419,
 0.11764957176360047,
 0.11749469908920933,
 0.11717498502967603,
 0.11712303424679456,
 0.11707322644771175,
 0.11689297502987947,
 0.11689297502987947,
 0.11654330934961299,
 0.11654330934961299,
 0.1164681928033949,
 0.11615078990692514,
 0.11615078990692514,
 0.11615078990692514,
 0.11589658124319134,
 0.11589658124319134,
 0.11561466260321597,
 0.11518482478021624,
 0.11470786693528089,
 0.11470786693528087,
 0.11470786693528087,
 0.11470786693528087,
 0.11470786693528087,
 0.11470786693528087,
 0.11470786693528087,
 0.11470786693528086,
 0.11243619908556621,
 0.11243619908556621,
 0.11243619908556621,
 0.11211037093424207,
 0.11211037093424207,
 0.11211037093424206,
 0.11164843913471803,
 0.11164843913471803,
 0.11141412945539658,
 0.11134983352076111,
 0.11134983352076111,
 0.11134983352076111,
 0.11132340659894101,
 0.11128297681493142,
 0.1106817677872384,
 0.11047363533322148,
 0.11047363533322148,
 0.11037769642208697,
 0.11037769642208697,
 0.11029436104106954,
 0.11029436104106954,
 0.11029436104106953,
 0.11024280153951839,
 0.11020775375559674,
 0.11020775375559674,
 0.10968169942141635,
 0.10926834468453095,
 0.10926834468453095,
 0.10926834468453095,
 0.10926834468453095,
 0.10926834468453095,
 0.10882143751650174,
 0.10838874619051499,
 0.10838874619051497,
 0.10838874619051497,
 0.10814761408717503,
 0.10814761408717503,
 0.10814761408717503,
 0.10814761408717502,
 0.10814761408717502,
 0.10814761408717502,
 0.108147614087175,
 0.1074861545850028,
 0.10740432270821094,
 0.10729938440986903,
 0.10729938440986901,
 0.10729938440986901,
 0.10705186531570646,
 0.10667614941253299,
 0.10651633486674561,
 0.10650358071057624,
 0.10650358071057624,
 0.10650358071057624,
 0.10635399695598369,
 0.10635399695598369,
 0.1061988488107183,
 0.10591900946051636,
 0.10591900946051634,
 0.10536590380294057,
 0.10526315789473682,
 0.10526315789473682,
 0.10526315789473682,
 0.10495671428119792,
 0.10495671428119792,
 0.10495671428119792,
 0.10471347707292386,
 0.10471347707292385,
 0.1039048666932262,
 0.1039048666932262,
 0.1037571695799112,
 0.10375716957991118,
 0.10375716957991118,
 0.10375716957991118,
 0.10375716957991118,
 0.10366105360784116,
 0.10366105360784116,
 0.10366105360784114,
 0.1032370802417528,
 0.10288402219457805,
 0.10280786170305815,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.1025978352085154,
 0.1025978352085154,
 0.1025978352085154,
 0.10197539568091137,
 0.10197539568091137,
 0.10147651372376074,
 0.10138838820672658,
 0.10138838820672658,
 0.10138838820672658,
 0.10138838820672658,
 0.10133891838762797,
 0.10116282977781398,
 0.10116282977781398,
 0.10072659303317578,
 0.10039117221153819,
 0.10039117221153819,
 0.10039117221153819,
 0.10039117221153819,
 0.10036938356837077,
 0.10036938356837077,
 0.10036938356837076,
 0.10012523486435176,
 0.10012523486435176,
 0.10012523486435176,
 0.09984038297885897,
 0.09984038297885897,
 0.09959431881428264,
 0.09959431881428264,
 0.09959431881428264,
 0.0993399267798783,
 0.0993399267798783,
 0.09933992677987828,
 0.09895413919905867,
 0.09895413919905867,
 0.09883693657685835,
 0.0983611844205792,
 0.0983611844205792,
 0.0983611844205792,
 0.09832102880166932,
 0.09832102880166932,
 0.09809657456746182,
 0.09733285267845751,
 0.09694584179118515,
 0.09694584179118515,
 0.09694584179118515,
 0.09694584179118515,
 0.09694584179118515,
 0.09666443091656879,
 0.09637388493048532,
 0.09637388493048532,
 0.09637388493048532,
 0.09637388493048532,
 0.09619721404877635,
 0.09597148699373931,
 0.09567297464698797,
 0.09567297464698797,
 0.09567297464698797,
 0.09567297464698797,
 0.09567297464698797,
 0.09558988911273406,
 0.09558988911273406,
 0.09558988911273406,
 0.09558988911273406,
 0.09558988911273406,
 0.09558988911273406,
 0.09544271444636666,
 0.09544271444636666,
 0.09544271444636666,
 0.09544271444636666,
 0.09544271444636666,
 0.09529323477053277,
 0.09529323477053275,
 0.09529323477053275,
 0.09462916232627815,
 0.09462916232627815,
 0.09453802374948818,
 0.09453802374948816,
 0.09453802374948816,
 0.09453802374948816,
 0.09453802374948816,
 0.09453802374948816,
 0.09428928580058928,
 0.09428928580058928,
 0.09428928580058928,
 0.09415023063157009,
 0.09404801560780578,
 0.09397878236968457,
 0.09397878236968457,
 0.0936585811581694,
 0.0936585811581694,
 0.09365858115816939,
 0.09365858115816939,
 0.09334163073596637,
 0.09334163073596637,
 0.09317455424271592,
 0.09308574042571362,
 0.09304036594559836,
 0.09304036594559835,
 0.09304036594559835,
 0.09304036594559835,
 0.09304036594559835,
 0.09280323373346189,
 0.09280323373346189,
 0.09280323373346189,
 0.09271726499455304,
 0.09222859518214328,
 0.09222859518214328,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274486,
 0.09183979479633063,
 0.09183979479633061,
 0.0917662935482247,
 0.0917662935482247,
 0.09176629354822469,
 0.09154684414630489,
 0.09150522248280035,
 0.09116056881941459,
 0.09116056881941459,
 0.09116056881941459,
 0.09091675835657292,
 0.09086217008485094,
 0.09086217008485092,
 0.09068453126375145,
 0.09068453126375145,
 0.09037128496931668,
 0.09037128496931668,
 0.09033950326094177,
 0.09019865580506051,
 0.0899842541331695,
 0.0899842541331695,
 0.0899842541331695,
 0.0899842541331695,
 0.0899842541331695,
 0.08977310580745097,
 0.08960215366342483,
 0.08960215366342483,
 0.08960215366342483,
 0.08957179548750233,
 0.08957179548750233,
 0.08957179548750233,
 0.08921722983855178,
 0.08918325397005952,
 0.08885233166386383,
 0.08885233166386383,
 0.08885233166386383,
 0.08885233166386383,
 0.08885233166386383,
 0.08885233166386383,
 0.08849904067559858,
 0.08849904067559858,
 0.08849904067559858,
 0.08830215713766958,
 0.08830215713766958,
 0.08820139006486122,
 0.08813576890402881,
 0.08812102431690699,
 0.08812102431690699,
 0.08812102431690699,
 0.08812102431690699,
 0.08746392856766494,
 0.08746392856766494,
 0.08746392856766494,
 0.08740748201220974,
 0.08740748201220974,
 0.08740748201220974,
 0.08709270531385191,
 0.08709270531385191,
 0.08671099695241198,
 0.08671099695241198,
 0.08646430798325933,
 0.08646430798325933,
 0.08646430798325933,
 0.08646430798325933,
 0.08646430798325933,
 0.08646430798325933,
 0.08646430798325933,
 0.08608581939007431,
 0.08603090020146066,
 0.08603090020146066,
 0.08603090020146066,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08559529790779072,
 0.08549819600709617,
 0.08549819600709617,
 0.08549819600709617,
 0.08549819600709617,
 0.08549819600709617,
 0.08536655898367083,
 0.08536655898367083,
 0.08536655898367083,
 0.08536655898367083,
 0.08520286456846099,
 0.08520286456846099,
 0.08520286456846099,
 0.08520286456846099,
 0.08520286456846099,
 0.08520286456846099,
 0.08471737420873574,
 0.08456376143646728,
 0.08456376143646728,
 0.08408277820068157,
 0.08408277820068155,
 0.08408277820068155,
 0.08408277820068155,
 0.0837707816583391,
 0.08377078165833908,
 0.08377078165833908,
 0.08377078165833908,
 0.08377078165833908,
 0.08365931017628182,
 0.08365931017628182,
 0.08365931017628182,
 0.08365931017628182,
 0.08365931017628182,
 0.08365931017628182,
 0.08365931017628182,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119856,
 0.08326256191221613,
 0.08326256191221613,
 0.08326256191221613,
 0.08326256191221613,
 0.08326256191221613,
 0.08299969954163149,
 0.08285522649991611,
 0.08285522649991611,
 0.08285522649991611,
 0.08278327231656525,
 0.08278327231656524,
 0.08278327231656524,
 0.08278327231656524,
 0.08278327231656524,
 0.08278327231656524,
 0.08240856434303291,
 0.08240856434303291,
 0.08240856434303291,
 0.08240856434303291,
 0.08240856434303291,
 0.08238145180262384,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08193419066805777,
 0.08193419066805777,
 0.08193419066805777,
 0.08193419066805777,
 0.08193419066805777,
 0.08193419066805777,
 0.08193419066805777,
 0.08193419066805775,
 0.08167991551759951,
 0.08152773496237643,
 0.08111071056538127,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08070002078437538,
 0.0805532420311582,
 0.0805532420311582,
 0.0805532420311582,
 0.08031157077540443,
 0.08031157077540443,
 0.08031157077540443,
 0.08031157077540443,
 0.08000711205939974,
 0.07987230638308718,
 0.07987230638308718,
 0.07987230638308718,
 0.07987230638308718,
 0.07953559537197222,
 0.07953559537197222,
 0.07953559537197222,
 0.07953559537197222,
 0.07950439882424458,
 0.07947194142390261,
 0.07947194142390261,
 0.07947194142390261,
 0.07911751380897428,
 0.07911751380897428,
 0.07897985036787898,
 0.07894736842105261,
 0.07894736842105261,
 0.07894736842105261,
 0.07894736842105261,
 0.07894736842105261,
 0.07878168645790681,
 0.07878168645790681,
 0.07868894753646336,
 0.07868894753646336,
 0.07868894753646336,
 0.07868894753646336,
 0.07868894753646336,
 0.07868894753646336,
 0.07836039099693788,
 0.07804881763180782,
 0.07804881763180782,
 0.07804881763180782,
 0.07804881763180782,
 0.0778050909600881,
 0.07762459638285141,
 0.07755667343294813,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.0774338599379501,
 0.07743385993795009,
 0.07733602811121824,
 0.07733602811121824,
 0.07733602811121824,
 0.0770085628656519,
 0.07694837640638655,
 0.07694837640638655,
 0.07694837640638655,
 0.07690914705058355,
 0.07673882976766815,
 0.07664241743562072,
 0.07664241743562072,
 0.07647191129018724,
 0.07647191129018724,
 0.07647191129018724,
 0.07647191129018724,
 0.07647191129018724,
 0.07647191129018724,
 0.07647191129018724,
 0.07647191129018724,
 0.07621312235413488,
 0.07596714068284549,
 0.07596714068284549,
 0.07596714068284548,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.0754314286404714,
 0.07530940414109723,
 0.07530940414109723,
 0.07530940414109723,
 0.07530940414109723,
 0.07509392614826382,
 0.07509392614826382,
 0.07509392614826382,
 0.07466846138618737,
 0.07466846138618737,
 0.07466846138618737,
 0.07466846138618737,
 0.07466846138618737,
 0.07466846138618737,
 0.07466846138618737,
 0.07466846138618737,
 0.07466846138618737,
 0.07455250649740336,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.074215604399294,
 0.074215604399294,
 0.07404360971988654,
 0.07404360971988652,
 0.07404360971988652,
 0.07378784519149227,
 0.0734718358370645,
 0.0734718358370645,
 0.0734718358370645,
 0.0734718358370645,
 0.0734718358370645,
 0.0734718358370645,
 0.0734718358370645,
 0.07343418693075583,
 0.07343418693075583,
 0.07343418693075583,
 0.07343418693075583,
 0.07343418693075583,
 0.07336739820667776,
 0.07336739820667776,
 0.07336739820667776,
 0.07336739820667776,
 0.07336739820667776,
 0.07336739820667776,
 0.07299591532245146,
 0.07299591532245146,
 0.07283956834350812,
 0.07283956834350812,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07225916412700999,
 0.07214791053658226,
 0.07175473098524097,
 0.07175473098524097,
 0.07175473098524097,
 0.07175473098524097,
 0.07175473098524097,
 0.07175473098524097,
 0.07175473098524097,
 0.07175473098524097,
 0.07175473098524097,
 0.07175473098524097,
 0.07175473098524097,
 0.07169241683455055,
 0.07169241683455055,
 0.07169241683455055,
 0.07169241683455055,
 0.07165743639000186,
 0.07165743639000186,
 0.07165743639000186,
 0.07165743639000186,
 0.07165743639000186,
 0.07165743639000186,
 0.07165743639000186,
 0.07113879915305903,
 0.07113879915305903,
 0.07113879915305903,
 0.07113879915305903,
 0.07113879915305903,
 0.07113879915305903,
 0.07079923254047886,
 0.07079923254047886,
 0.07079923254047886,
 0.07059781184061312,
 0.07059781184061312,
 0.07059781184061312,
 0.07059781184061312,
 0.07059781184061312,
 0.07024393586862705,
 0.07024393586862705,
 0.07024393586862705,
 0.07024393586862705,
 0.07024393586862705,
 0.0700689818339013,
 0.06997114285413195,
 0.06997114285413195,
 0.06997114285413195,
 0.06955186050933214,
 0.06955186050933214,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.0691073690718941,
 0.06904602208326342,
 0.06904602208326342,
 0.06904602208326342,
 0.06904602208326342,
 0.06904602208326342,
 0.06904602208326342,
 0.06904602208326342,
 0.06904602208326342,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116851,
 0.06855106213838522,
 0.06855106213838522,
 0.06855106213838522,
 0.06855106213838522,
 0.06855106213838522,
 0.06839855680567694,
 0.06839855680567694,
 0.06839855680567694,
 0.06839855680567693,
 0.06806659626466625,
 0.06806659626466625,
 0.06765100914917382,
 0.06765100914917382,
 0.06765100914917382,
 0.06765100914917382,
 0.0675922588044844,
 0.0675922588044844,
 0.0675922588044844,
 0.0675922588044844,
 0.06759225880448438,
 0.06748819059987712,
 0.06748819059987712,
 0.06748819059987712,
 0.06748819059987712,
 0.06716604942594676,
 0.06712770169263184,
 0.06692744814102546,
 0.06692744814102546,
 0.06692744814102546,
 0.06692744814102546,
 0.06692744814102546,
 0.06692744814102546,
 0.06692744814102546,
 0.06684847767323795,
 0.06667259338283311,
 0.06667259338283311,
 0.06667259338283311,
 0.06667259338283311,
 0.06653536832815836,
 0.06622661785325219,

In [51]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(2409, 0.490079493105597),
 (4336, 0.4113063728303113),
 (1537, 0.3880712182748949),
 (3162, 0.3879852850993631),
 (373, 0.380442955126341)]

In [52]:
def recommend(movie):
    mv_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[mv_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [55]:
recommend('Avatar')

Aliens
Silent Running
Moonraker
Alien
Mission to Mars

In [56]:
import pickle

In [57]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [59]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [60]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [61]:
pickle.dump(similarity,open('similarity.pkl','wb'))